### PR TITLE
Standardizing code comments

### PR DESCRIPTION
**Pull request by andrsd**

### CODE REVIEW

**Comment by andrsd** [comment]
This is a preview of what #340 would enforce. I will keep working on `lua` and `modules` meanwhile...

**Comment by andrsd** [comment]
NOTE: I am also converting these comments:
```
  double evaluation_time_ = 0.0; ///< Time value passed to boundary functions
```
into:
```
/// Time value passed to boundary functions
double evaluation_time_ = 0.0; 
```

The comments after the variables usually don't play nice with clang-format hem they get lengthy

**Comment by ragusa** [comment]
looks good to me

**Review by ragusa — APPROVED** [review]

**Review by zhardy-lanl — APPROVED** [review]
This is great! Thank you!

**Review by wdhawkins — APPROVED** [review]

**Pull request merged**
