### PR TITLE
Fixing a typo in lua instructions for linux installation

### LINKED ISSUE #451: Fix typo in linux installation instructions
This needs to be fixed:
https://github.com/Open-Sn/opensn/blob/114fb361f37428f2210a5bde460610307aaf65eb/doc/install_linux.md?plain=1#L140

So it says:
```
make linux MYCFLAGS=-fPIC -j
```

### PR DESCRIPTION
**Pull request by andrsd**
Closes #451

### CODE REVIEW

**Review by ragusa — APPROVED** [review]
Is this why a .a instead of a .so was created on linux?

**Comment by andrsd** [comment]
> Is this why a .a instead of a .so was created on linux?

`.a` is a static library, `.so` is a dynamic library.

**Comment by andrsd** [comment]
No, lua builds a static library with the provided Makefile. For a dynamic library, the build system must be patched. For example, conda does [that](https://github.com/conda-forge/lua-feedstock/blob/main/recipe/liblua.so.patch)

**Review by wdhawkins — APPROVED** [review]

**Comment by ragusa** [comment]
i think 2 reviewers are enough for this. merging soon.

**Review by zhardy-lanl — APPROVED** [review]

**Pull request merged**
