### PR TITLE
Updating configure_dependencies.py to PETSc 3.20.6

### PR DESCRIPTION
**Pull request by wdhawkins**
This PR updates configure_dependencies.py to use PETSc 3.20.6 and includes other minor changes to successfully build on macOS 14.5+.

### CODE REVIEW

**Review by ragusa — APPROVED** [review]
Why was fopenmp removed (or why could it have been there before)?

**Comment by andrsd** [comment]
Apple does not support openmp at all. We usually get it if we are using homebrew, conda, etc. So, this could be it. Moreover, we are not using openmp anywhere and PETSc internally does not do threading either. They leave it to the application to deal with that. This is probably why we are able to remove this flag with no harm.

**Review by andrsd — APPROVED** [review]

**Comment by wdhawkins** [comment]
David is correct. Apple clang doesn't support openmp, and it's not used in OpenSn or PETSc. With these changes, OpenSn and dependencies will compile with the Apple toolchain and a suitable MPI implementation.

**Review by zhardy-lanl — APPROVED** [review]
Looks like there is a Python formatting issue, FYI

**Pull request merged**
