### PR TITLE
Generate JSON compile commands database

### PR DESCRIPTION
**Pull request by wdhawkins**
This PR adds functionality to CMakeLists.txt to always generate a JSON compile commands database for use with various tools.

### CODE REVIEW

**Comment by andrsd** [comment]
Just out of curiosity, why is this not enabled from command line when you need it via `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`?

**Comment by ragusa** [comment]
good question @andrsd . maybe what we should do instead is add a note in the install instructions so that people can turn it on if they want without forcing the export each time for everybody. what do you think @wdhawkins ?

**Comment by wdhawkins** [comment]
Adding `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` will also work. However, since this is a completely innocuous change and enables so much additional code quality functionality, I think it's worthwhile to enable it by default. It adds one additional file to the `build` directory and doesn't slow down compilation. 

In the next week or so, I will have a PR with an initial version of a `clang-tidy` config that requires this functionality. The first set of fixes numbers in the few hundreds, but we will be "tidy" clean after that (at least with our config). This is something that we need to incorporate into our development workflow, IMO, and it'll be easier if we don't have to remember to compile with `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` every time.

**Comment by ragusa** [comment]
Ok. I am good with adding this to the repo then!! tag for info: @wdhawkins @andrsd

**Comment by andrsd** [comment]
I see. If this is a prep for `clang-tidy` then this is fine. I saw something like this used for rtags, which was an editor-specific thing, so that's why I asked...

**Review by andrsd — APPROVED** [review]

**Review by zhardy-lanl — APPROVED** [review]

**Pull request merged**
