### PR TITLE
Removing kernel/callback system from LBS sweep chunks

### LINKED ISSUE #116: remove Kernels in the code
example: [modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc](https://github.com/Open-Sn/opensn/blob/fac8cc89d77d80520ff8eccbceba7e321cda7dfa/modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc#L53)

### PR DESCRIPTION
**Pull request by wdhawkins**
Fixes #116

### CODE REVIEW

**Review by zhardy-lanl — APPROVED** [review]

**Review by ragusa — APPROVED** [review]
so, no more word "kernel" anywhere? 🥇

**Comment by wdhawkins** [comment]
> so, no more word "kernel" anywhere? 🥇

That is correct. It looks like they were only used in LBS sweep chunks.

**Review by andrsd — APPROVED** [review]
Nice :+1:

**Comment by andrsd** [comment]
After this was merged, I see these warnings reported by clang:
```
In file included from <opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc:1:
<opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:17:45: warning: private field 'secondary_unit_cell_matrices_' is not used [-Wunused-private-field]
  const std::vector<lbs::UnitCellMatrices>& secondary_unit_cell_matrices_;
                                            ^
<opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:28:17: warning: private field 'Maux_' is not used [-Wunused-private-field]
  const MatDbl* Maux_ = nullptr;
                ^
<opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:30:16: warning: private field 'polar_level_' is not used [-Wunused-private-field]
  unsigned int polar_level_ = 0;
               ^
/Users/andrsd/devel/openSn/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:31:10: warning: private field 'fac_diamond_difference_' is not used [-Wunused-private-field]
  double fac_diamond_difference_ = 0.0;
         ^
<opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:32:10: warning: private field 'fac_streaming_operator_' is not used [-Wunused-private-field]
  double fac_streaming_operator_ = 0.0;
         ^
5 warnings generated.
```
They seem legit.

@wdhawkins I know you are planing/already doing more refactoring in the sweep code. So this is just a note that this may need some more attention on the clean up front.

**Comment by wdhawkins** [comment]
> After this was merged, I see these warnings reported by clang:
> 
> ```
> In file included from <opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc:1:
> <opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:17:45: warning: private field 'secondary_unit_cell_matrices_' is not used [-Wunused-private-field]
>   const std::vector<lbs::UnitCellMatrices>& secondary_unit_cell_matrices_;
>                                             ^
> <opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:28:17: warning: private field 'Maux_' is not used [-Wunused-private-field]
>   const MatDbl* Maux_ = nullptr;
>                 ^
> <opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:30:16: warning: private field 'polar_level_' is not used [-Wunused-private-field]
>   unsigned int polar_level_ = 0;
>                ^
> /Users/andrsd/devel/openSn/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:31:10: warning: private field 'fac_diamond_difference_' is not used [-Wunused-private-field]
>   double fac_diamond_difference_ = 0.0;
>          ^
> <opensn>/modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h:32:10: warning: private field 'fac_streaming_operator_' is not used [-Wunused-private-field]
>   double fac_streaming_operator_ = 0.0;
>          ^
> 5 warnings generated.
> ```
> 
> They seem legit.
> 
> @wdhawkins I know you are planing/already doing more refactoring in the sweep code. So this is just a note that this may need some more attention on the clean up front.

Interesting. I don't see those warnings. It may be the version of clang I'm using. In my experience, warnings are very much dependent on compiler and even compiler version. I'm working on a commit for today, and I'll get these cleaned up.

**Comment by andrsd** [comment]
My clang is 14.0.6 from `conda`. `conda` sets these flags in the environment `-ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0` and cmake picks that up, so may be this could help you trigger those warnings.

**Pull request merged**
