### PR TITLE
Adding support for Scotch partitioner via PETSc

### LINKED ISSUE #50: parallel mesh partitioners
Add scotch in addition to parmetis.

### PR DESCRIPTION
**Pull request by wdhawkins**
This PR updates the PETSc install instructions to install the Scotch graph partitioner. It also adds Scotch to the PETSc install in configure_dependencies.py. I have tested the Scotch partitioner on multiple transport problems with no issues. 

Closes #50.

### CODE REVIEW

**Review by ragusa — COMMENTED** [review]
Shouldn't this PR also add a test case where scotch is actually called as the partitioner?

**Comment by andrsd** [comment]
> Shouldn't this PR also add a test case where scotch is actually called as the partitioner?

It could be that he needs to update the build machine to have ptscotch available (IDK if it there yet). Otherwise, the tests would be failing on our CI pipeline...

**Comment by ragusa** [comment]
I think it would be complete to add the test. An example of explicit calling of the PETSc partitioner is below. Adapt as needed but you will need to replace the "type" from `pametis `to whatever PETSc requests for `scotch`.
`
meshgen = mesh.MeshGenerator.Create
({
  inputs =
  {
    mesh.FromFileMeshGenerator.Create
    ({
      filename="../../../../resources/TestMeshes/GMSH_AllTets.vtu"
    }),
  },
  partitioner = PETScGraphPartitioner.Create({type="parmetis"})
})
mesh.MeshGenerator.Execute(meshgen)
`

**Comment by wdhawkins** [comment]
I'll add some tests. I tested it on some of the existing transport problems, and it worked fine. I'll recompile the CI PETSc this afternoon.

**Comment by zhardy-lanl** [comment]
Should we add something into configure to check for a PETSc build with scotch? This change will result in the regression suite failing for anyone running on a different machine who does not have a PETSc build with scotch won't it?

**Comment by andrsd** [comment]
Roughly this:
```
check_symbol_exists(PETSC_HAVE_PTSCOTCH "${PETSC_INCLUDE_DIR}/petscconf.h" PETSC_HAVE_PTSCOTCH)
if(NOT ${PETSC_HAVE_PTSCOTCH} MATCHES 1)
    message(FATAL_ERROR "PETSc has not been configured with the PTSCOTCH\n")
endif()
```
around line 78 in the main `CMakeLists.txt` should do it.

**Comment by zhardy-lanl** [comment]
> Roughly this:
> 
> ```
> check_symbol_exists(PETSC_HAVE_PTSCOTCH "${PETSC_INCLUDE_DIR}/petscconf.h" PETSC_HAVE_PTSCOTCH)
> if(NOT ${PETSC_HAVE_PTSCOTCH} MATCHES 1)
>     message(FATAL_ERROR "PETSc has not been configured with the PTSCOTCH\n")
> endif()
> ```
> 
> around line 78 in the main `CMakeLists.txt` should do it.

That would be great. We should consider doing this will the other PETSc dependencies as well, just to be more robust and help catch errors, but that can be punted to a future PR.

**Review by ragusa — APPROVED** [review]

**Comment by ragusa** [comment]
@wdhawkins your new test is failing the regression suite?

**Comment by wdhawkins** [comment]
> @wdhawkins your new test is failing the regression suite?

Yeah, that was a typo in the test. I forgot to update the boundary condition.  Fixed.

**Review by andrsd — CHANGES_REQUESTED** [review]

**Review by andrsd — APPROVED** [review]

**Comment by andrsd** [comment]
:+1: on using `fixup` to correct the original patch and incorporating changes I asked for rather than a new patch.

**Comment by wdhawkins** [comment]
> 👍 on using `fixup` to correct the original patch and incorporating changes I asked for rather than a new patch.

I'm learning. :smile:  Different workflow for me, but I do like it.

**Review by zhardy-lanl — APPROVED** [review]

**Pull request merged**
